#SPDX-License-Identifier: MIT-0
---
# tasks file for users
- name: Add user, group, and ssh login authorized
  vars:
    new_user: ansible
  block:
    - name: Add group
      group: name={{ new_user }} state=present

    - name: Add user
      user: name={{ new_user }} group={{ new_user }}  shell=/bin/bash

    - name: Create .ssh directory and add authorized key
      authorized_key:
        user: { { new_user } }
        state: present
        key: "{{ lookup('file', '/opt/ansible/keys/east.pub') }}"
      # when: hostnamefix == "east"

    - name: Set user directory permission
      file: path={{ item }} owner={{ new_user }} group={{ new_user }} mode=0755 recurse=yes state=directory
      loop:
        - /data/
        - /web/
