commonAnnotations:
  note: base-env
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - literals:
    - FOO=Bar
    name: example-configmap-1
secretGenerator:
  - literals:
    - username=admin
    - password=secret
    name: example-secret-1
generatorOptions:
  annotations:
    note: generate
  disableNameSuffixHash: true
  labels:
    type: generated
