{
 "title": "Kubernetes Statefulset Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas,namespace)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas{namespace=\"$namespace\"},statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Percent",
   "type": "timeseries",
   "description": "Pods CPU usage for selected workload",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",container!=\"\"}[2m])) by (pod) / max(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",resource=\"cpu\"}) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MEMORY Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",container!=\"\"}) by (pod)/ max(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",resource=\"memory\"}) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$statefulset.*\",image!~\".*pause.*\",container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}