apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: my-nginx
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
