name: Publish to Multi-Registry

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy env"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Version"
        required: false
        type: string

env:
  ACR_REGISTRY: crpi-fkl1s7fwluzapj2o.cn-hongkong.personal.cr.aliyuncs.com
  DOCKERHUB_REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-multi-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [acr, dockerhub, ghcr]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
      #   with:
      #     cosign-release: "v2.2.4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v4.3.0

      - name: Set up Registry Variables
        id: vars
        run: |
          case "${{ matrix.registry }}" in
            acr)
              echo "REGISTRY=${{ env.ACR_REGISTRY }}" >> $GITHUB_ENV
              ;;
            dockerhub)
              echo "REGISTRY=${{ env.DOCKERHUB_REGISTRY }}" >> $GITHUB_ENV
              ;;
            ghcr)
              echo "REGISTRY=${{ env.GHCR_REGISTRY }}" >> $GITHUB_ENV
              ;;
          esac

      - name: Log into registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{
            matrix.registry == 'acr' && secrets.ACR_PWD ||
            matrix.registry == 'dockerhub' && secrets.DOCKERHUB_TOKEN ||
            secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: ./APP-META/Docker/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Cleanup
      #   if: always()
      #   run: |
      #     docker buildx prune -a -f
      #     docker system prune -a -f

      # - name: Sign the published Docker image
      #   if: ${{ github.event_name != 'pull_request' }}
      #   env:
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #   run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
